# Generated by Django 2.1.5 on 2019-04-22 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('brandID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('goodsID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('photo', models.ImageField(upload_to='Home/GoodsP')),
                ('price', models.IntegerField()),
                ('introduce', models.TextField(null=True)),
                ('sale', models.IntegerField(null=True)),
                ('stroe', models.IntegerField(null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.brand')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('messageID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='notice',
            fields=[
                ('noticeID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=32)),
                ('avatar', models.ImageField(upload_to='Home/avatar')),
                ('sex', models.CharField(max_length=32)),
                ('password', models.TextField()),
                ('name', models.CharField(max_length=32)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.user'),
        ),
    ]
