# Generated by Django 2.1.5 on 2019-05-05 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.user')),
            ],
        ),
        migrations.CreateModel(
            name='orderList',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.order')),
            ],
        ),
    ]
